name: NextJS CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Build job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Install packages
        run: npm install

      - name: Test
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ksuphaky/watcher

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  update-gitops-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: biskitsx/watcher-infra
          token: ${{ secrets.GITOPS_PAT }}
          ref: main
      - name: Update image version
        run: |
          sed -i "/newName: ksuphaky\/watcher/{n;s/newTag: .*/newTag: {{ github.sha }}/;}" ./gitops/apps/watcher/overlay/dev/kustomization.yaml
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update watcher image tag to ${{ github.sha}}"
          git push origin main